import mongoose from 'mongoose';

const AmazonMarketplaceSchema = new mongoose.Schema(
  {
    variationThemeName: { type: String, trim: true },
    modelNumber: { type: String, trim: true },
    modelName: { type: String, trim: true },
    style: { type: String, trim: true },
    bulletPoint: { type: String, trim: true },
    footwearSizeSystem: { type: String, trim: true },
    footwearAgeGroup: { type: String, trim: true },
    footwearSizeClass: { type: String, trim: true },
    footwearWidth: { type: String, trim: true },
    footwearSize: { type: String, trim: true },
    soleMaterial: { type: String, trim: true },
    toeStyle: { type: String, trim: true },
    heightMap: { type: String, trim: true },
    heelType: { type: String, trim: true },
    waterResistanceLevel: { type: String, trim: true },
    closure: { type: String, trim: true },
    shaftCircumference: { type: String, trim: true },
    shaftHeight: { type: String, trim: true },
    skipOffer: { type: String, trim: true },
    itemCondition: { type: String, trim: true },
    listPriceCurrency: { type: String, trim: true },
    dangerousGoodsRegulations: { type: String, trim: true },
    outerMaterial: { type: String, trim: true },
    departmentName: { type: String, trim: true },
    sizeSystem: { type: String, trim: true },
    sizeClass: { type: String, trim: true },
    bodyType: { type: String, trim: true },
    heightType: { type: String, trim: true },
    fabricType: { type: String, trim: true },
    specialSize: { type: String, trim: true },
    weaveType: { type: String, trim: true },
    careInstructions: { type: String, trim: true },
    shippingTemplateSA: { type: String, trim: true },
    fitType: { type: String, trim: true },
    riseStyle: { type: String, trim: true },
    closureType: { type: String, trim: true },
    occasion: { type: String, trim: true },
    subtype: { type: String, trim: true },
  },
  { _id: false }
);

export default AmazonMarketplaceSchema;
