import mongoose from 'mongoose';

const AmazonMarketplaceSchema = new mongoose.Schema(
  {
    variationThemeName: { type: String, trim: true },
    modelNumber: { type: String, trim: true },
    modelName: { type: String, trim: true },
    style: { type: String, trim: true },
    bulletPoint: { type: String, trim: true },
    footwearSizeSystem: { type: String, trim: true },
    footwearAgeGroup: { type: String, trim: true },
    footwearSizeClass: { type: String, trim: true },
    footwearWidth: { type: String, trim: true },
    footwearSize: { type: String, trim: true },
    soleMaterial: { type: String, trim: true },
    toeStyle: { type: String, trim: true },
    heightMap: { type: String, trim: true },
    heelType: { type: String, trim: true },
    waterResistanceLevel: { type: String, trim: true },
    closure: { type: String, trim: true },
    shaftCircumference: { type: String, trim: true },
    shaftHeight: { type: String, trim: true },
    skipOffer: { type: String, trim: true },
    itemCondition: { type: String, trim: true },
    listPriceCurrency: { type: String, trim: true },
    dangerousGoodsRegulations: { type: String, trim: true },
    outerMaterial: { type: String, trim: true },
    departmentName: { type: String, trim: true },
    sizeSystem: { type: String, trim: true },
    sizeClass: { type: String, trim: true },
    bodyType: { type: String, trim: true },
    heightType: { type: String, trim: true },
    fabricType: { type: String, trim: true },
    specialSize: { type: String, trim: true },
    weaveType: { type: String, trim: true },
    careInstructions: { type: String, trim: true },
    shippingTemplateSA: { type: String, trim: true },
    fitType: { type: String, trim: true },
    riseStyle: { type: String, trim: true },
    closureType: { type: String, trim: true },
    occasion: { type: String, trim: true },
    subtype: { type: String, trim: true },
    sleeveType: { type: String, trim: true },
    neck: { type: String, trim: true },
    material: { type: String, trim: true },
    pattern: { type: String, trim: true },
    amazonImages: [{ type: String, trim: true }],
    amazonPrimaryImageUrl: { type: String, trim: true },
    amazonImageUrl: { type: String, trim: true },
    amazonExtraImageUrl1: { type: String, trim: true },
    amazonExtraImageUrl2: { type: String, trim: true },
    amazonExtraImageUrl3: { type: String, trim: true },
    amazonExtraImageUrl4: { type: String, trim: true },
    amazonExtraImageUrl5: { type: String, trim: true },
    amazonExtraImageUrl6: { type: String, trim: true },
    amazonExtraImageUrl7: { type: String, trim: true },
    amazonExtraImageUrl8: { type: String, trim: true },
    amazonExtraImageUrl9: { type: String, trim: true },
    amazonExtraImageUrl10: { type: String, trim: true },
    amazonExtraImageUrl11: { type: String, trim: true },
    amazonExtraImageUrl12: { type: String, trim: true },
    amazonExtraImageUrl13: { type: String, trim: true },
    amazonExtraImageUrl14: { type: String, trim: true },
  },
  { _id: false }
);

export default AmazonMarketplaceSchema;
