export const CE_QUEUE_OPERATIONS = {
  PRODUCTS_PUSH: 'PRODUCTS_PUSH',
  PRODUCTS_FREEZE: 'PRODUCTS_FREEZE',
  PRODUCTS_BULK_DELETE: 'PRODUCTS_BULK_DELETE',
  PRODUCTS_EXTRA_DATA: 'PRODUCTS_EXTRA_DATA',
  OFFER_STOCK: 'OFFER_STOCK',
  OFFER_PRICE: 'OFFER_PRICE',
  ORDER_ACKNOWLEDGE: 'ORDER_ACKNOWLEDGE',
  ORDER_CANCELLATION: 'ORDER_CANCELLATION',
  SHIPMENT_CREATE: 'SHIPMENT_CREATE',
  SHIPMENT_DELIVERY_STATE: 'SHIPMENT_DELIVERY_STATE',
  RETURN_MERCHANT_CREATE: 'RETURN_MERCHANT_CREATE',
  RETURN_MERCHANT_ACKNOWLEDGE: 'RETURN_MERCHANT_ACKNOWLEDGE',
  RETURN_ACCEPT_REJECT: 'RETURN_ACCEPT_REJECT',
};

export const CE_QUEUE_STATUSES = ['queued', 'active', 'retrying', 'completed', 'failed'];

export const CHANNEL_ENGINE_QUEUE_NAME = 'channel-engine-push';
