export const CE_QUEUE_OPERATIONS = {
  PRODUCTS_PUSH: 'PRODUCTS_PUSH',
  PRODUCTS_FREEZE: 'PRODUCTS_FREEZE',
  PRODUCTS_BULK_DELETE: 'PRODUCTS_BULK_DELETE',
  PRODUCTS_EXTRA_DATA: 'PRODUCTS_EXTRA_DATA',
  OFFER_STOCK: 'OFFER_STOCK',
  OFFER_PRICE: 'OFFER_PRICE',
  ORDER_ACKNOWLEDGE: 'ORDER_ACKNOWLEDGE',
  ORDER_CANCELLATION: 'ORDER_CANCELLATION',
  SHIPMENT_CREATE: 'SHIPMENT_CREATE',
  SHIPMENT_DELIVERY_STATE: 'SHIPMENT_DELIVERY_STATE',
  RETURN_MERCHANT_CREATE: 'RETURN_MERCHANT_CREATE',
  RETURN_MERCHANT_ACKNOWLEDGE: 'RETURN_MERCHANT_ACKNOWLEDGE',
  RETURN_ACCEPT_REJECT: 'RETURN_ACCEPT_REJECT',
};

export const CE_QUEUE_GROUPS = {
  PRODUCTS: 'ce-products',
  STOCK: 'ce-stock',
  PRICE: 'ce-price',
  CANCELLATIONS: 'ce-cancellations',
  ORDERS_SHIPMENTS: 'ce-orders-shipments',
};

export const CE_OPERATION_TO_QUEUE_GROUP = {
  [CE_QUEUE_OPERATIONS.PRODUCTS_PUSH]: CE_QUEUE_GROUPS.PRODUCTS,
  [CE_QUEUE_OPERATIONS.PRODUCTS_FREEZE]: CE_QUEUE_GROUPS.PRODUCTS,
  [CE_QUEUE_OPERATIONS.PRODUCTS_BULK_DELETE]: CE_QUEUE_GROUPS.PRODUCTS,

  [CE_QUEUE_OPERATIONS.OFFER_STOCK]: CE_QUEUE_GROUPS.STOCK,

  [CE_QUEUE_OPERATIONS.OFFER_PRICE]: CE_QUEUE_GROUPS.PRICE,
  [CE_QUEUE_OPERATIONS.PRODUCTS_EXTRA_DATA]: CE_QUEUE_GROUPS.PRICE,

  [CE_QUEUE_OPERATIONS.ORDER_CANCELLATION]: CE_QUEUE_GROUPS.CANCELLATIONS,

  [CE_QUEUE_OPERATIONS.ORDER_ACKNOWLEDGE]: CE_QUEUE_GROUPS.ORDERS_SHIPMENTS,
  [CE_QUEUE_OPERATIONS.SHIPMENT_CREATE]: CE_QUEUE_GROUPS.ORDERS_SHIPMENTS,
  [CE_QUEUE_OPERATIONS.SHIPMENT_DELIVERY_STATE]: CE_QUEUE_GROUPS.ORDERS_SHIPMENTS,
  [CE_QUEUE_OPERATIONS.RETURN_MERCHANT_CREATE]: CE_QUEUE_GROUPS.ORDERS_SHIPMENTS,
  [CE_QUEUE_OPERATIONS.RETURN_MERCHANT_ACKNOWLEDGE]: CE_QUEUE_GROUPS.ORDERS_SHIPMENTS,
  [CE_QUEUE_OPERATIONS.RETURN_ACCEPT_REJECT]: CE_QUEUE_GROUPS.ORDERS_SHIPMENTS,
};

export function getQueueGroupForOperation(operationType) {
  return CE_OPERATION_TO_QUEUE_GROUP[operationType] || CE_QUEUE_GROUPS.ORDERS_SHIPMENTS;
}

export const CE_QUEUE_STATUSES = ['queued', 'active', 'retrying', 'completed', 'failed'];

// Default queue fallback for legacy references
export const CHANNEL_ENGINE_QUEUE_NAME = 'ce-orders-shipments';
