// Maps CSV header names → FinanceRecord model field names
export const FINANCE_HEADER_MAP = {
  Marketplace: 'marketplace',
  'Order ID': 'orderId',
  Item_Ref: 'itemRef',
  AWB: 'awb',
  brand: 'brand',
  SKU: 'sku',
  Title: 'title',
  'SKU Status': 'skuStatus',
  'Order Date': 'orderDate',
  'Delivered Date': 'deliveredDate',
  'Chargable Weight': 'chargeableWeight',
  'Item Price': 'itemPrice',
  'Total Order \nAmount': 'totalOrderAmount',
  'Total Delivered \norders Amount': 'totalDeliveredOrdersAmount',
  'Order Amount (Without VAT)': 'orderAmountWithoutVAT',
  'Logistic Price Shared with Customer': 'logisticPriceSharedWithCustomer',
  'Actual Logistic Price': 'actualLogisticPrice',
  'Logistics Price Difference': 'logisticsPriceDifference',
  'Admin Charges': 'adminCharges',
  'Marketplace Commission Shared with Customer': 'marketplaceCommissionSharedWithCustomer',
  'Actual Marketplace Commission': 'actualMarketplaceCommission',
  'Marketplace Commission Difference': 'marketplaceCommissionDifference',
  'OllTek Fee': 'ollTekFee',
  'Marketing Fee 10%': 'marketingFee10Percent',
  'Total Costs for Brand': 'totalCostsForBrand',
  'What Customer Receives from OllTek': 'whatCustomerReceivesFromOllTek',
  'Import VAT': 'importVAT',
  'Marketplace Last Mile': 'marketplaceLastMile',
  'Actual End to End Logistics Cost': 'actualEndToEndLogisticsCost',
  'OllTek Investment/extra profit': 'ollTekInvestmentExtraProfit',
};

export const FINANCE_DATE_FIELDS = new Set(['orderDate', 'deliveredDate']);

export const FINANCE_NUMBER_FIELDS = new Set([
  'chargeableWeight',
  'itemPrice',
  'totalOrderAmount',
  'totalDeliveredOrdersAmount',
  'orderAmountWithoutVAT',
  'logisticPriceSharedWithCustomer',
  'actualLogisticPrice',
  'logisticsPriceDifference',
  'adminCharges',
  'marketplaceCommissionSharedWithCustomer',
  'actualMarketplaceCommission',
  'marketplaceCommissionDifference',
  'ollTekFee',
  'marketingFee10Percent',
  'totalCostsForBrand',
  'whatCustomerReceivesFromOllTek',
  'importVAT',
  'marketplaceLastMile',
  'actualEndToEndLogisticsCost',
  'ollTekInvestmentExtraProfit',
]);
