// Product Required fields
export const PRODUCT_REQUIRED_FIELDS = [
  'productSkuCode',
  'nameAr',
  'name',
  'description',
  'descriptionAr',
  'brand',
  'ean',
  'price',
  'vatRateType',
  'shippingCost',
  'categoryTrail',
  'primaryImageUrl',
  'currentStockCount',
  'volumetricWeightCm',
  'hsCodeAE',
  'hsCodeSA',
  'size',
  'color',
];
