export const mapProductToChannelEngine = (product) => {
  const customAttributes = [
    { Key: 'MarketPlace', Value: product.marketPlace || null, Type: 'TEXT', IsPublic: true, LanguageIsoCode: 'en' },
    { Key: 'Stock', Value: product.currentStockCount || null, Type: 'TEXT', IsPublic: true, LanguageIsoCode: 'en' },
    {
      Key: 'categoryTrailAmazon',
      Value: product.categoryTrailAmazon || null,
      Type: 'TEXT',
      IsPublic: true,
      LanguageIsoCode: 'en',
    },
    {
      Key: 'categoryTrailNoon',
      Value: product.categoryTrailNoon || null,
      Type: 'TEXT',
      IsPublic: true,
      LanguageIsoCode: 'en',
    },
    {
      Key: 'categoryTrailTrendyol',
      Value: product.categoryTrailTrendyol || null,
      Type: 'TEXT',
      IsPublic: true,
      LanguageIsoCode: 'en',
    },
    {
      Key: 'titleAr',
      Value: product.nameAr || null,
      Type: 'TEXT',
      IsPublic: true,
      LanguageIsoCode: 'ar',
    },
    {
      Key: 'hsCodeSA',
      Value: product.hsCodeSA || null,
      Type: 'TEXT',
      IsPublic: true,
      LanguageIsoCode: 'en',
    },
    {
      Key: 'hsCodeAE',
      Value: product.hsCodeAE || null,
      Type: 'TEXT',
      IsPublic: true,
      LanguageIsoCode: 'en',
    },
    {
      Key: 'volumetricWeightCm',
      Value: product.volumetricWeightCm || null,
      Type: 'TEXT',
      IsPublic: true,
      LanguageIsoCode: 'en',
    },
    {
      Key: 'longDescriptionAr',
      Value: product.descriptionAr || null,
      Type: 'TEXT',
      IsPublic: true,
      LanguageIsoCode: 'en',
    },
    {
      Key: 'status',
      Value: product.status || null,
      Type: 'TEXT',
      IsPublic: true,
      LanguageIsoCode: 'en',
    },
  ];
  const attributesString = product.attributes || null;
  return {
    ParentMerchantProductNo: product.parentProductSkuCode || null,
    ParentMerchantProductNo2: product.grandParentProductSkuCode || null,
    ExtraData: [
      { Key: 'Attributes', Value: attributesString, Type: 'TEXT', IsPublic: true, LanguageIsoCode: 'en' },
      ...customAttributes,
    ],
    Name: product.name || null,
    Description: product.description || null,
    Brand: product.brand || null,
    Size: product.size || null,
    Color: product.color || null,
    Ean: product.ean || null,
    Stock: product.currentStockCount || null,
    ManufacturerProductNumber: product.productSkuCode || null,
    MerchantProductNo: product.productSkuCode || null,
    Price: product.price || null,
    MinPrice: product.minPrice || null,
    MaxPrice: product.maxPrice || null,
    MSRP: product.msrp || null,
    PurchasePrice: product.purchasePrice || null,
    VatRateType: product.vatRateType || null,
    ShippingCost: product.shippingCost || null,
    ShippingTime: product.shippingTime || null,
    Url: product.primaryImageUrl || null,
    ImageUrl: product.imageUrl || null,
    CategoryTrail: product.categoryTrail || null,
    IsFrozen: false,
    ExtraImageUrl1: product.extraImageUrl1 || null,
    ExtraImageUrl2: product.extraImageUrl2 || null,
    ExtraImageUrl3: product.extraImageUrl3 || null,
  };
};
