import { exportExtraImageUrlValues, exportAmazonExtraImageUrlValues } from '#helpers/productImageFields.js';

export const buildProductExportCsvRow = (product) => {
  return [
    product.grandParentProductSkuCode || '',
    product.parentProductSkuCode || '',
    product.productSkuCode || '',
    product.brand || '',
    product.categoryTrail || '',
    product.color || '',
    product.currentStockCount || 0,
    product.description || '',
    product.descriptionAr || '',
    product.ean || '',
    ...exportExtraImageUrlValues(product),
    product.gender || '',
    product.hsCodeSA || '',
    product.hsCodeAE || '',
    product.imageUrl || '',
    product.maxPrice || 0,
    product.minPrice || 0,
    product.msrp || 0,
    product.name || '',
    product.nameAr || '',
    product.price || 0,
    product.primaryImageUrl || '',
    product.purchasePrice || 0,
    product.shippingCost || 0,
    product.shippingTime || '',
    product.size || '',
    product.vatRateType || '',
    product.volumetricWeightCm || 0,
    product.noonPrice || 0,
    product.namshiPrice || 0,
    product.amazonPrice || 0,
    product.sixthStreetPrice || 0,
    product.styliPrice || 0,
    product.amazon?.amazonPrimaryImageUrl || product.amazonPrimaryImageUrl || product.amazon?.primaryImageUrl || '',
    product.amazon?.amazonImageUrl || product.amazonImageUrl || product.amazon?.imageUrl || '',
    ...exportAmazonExtraImageUrlValues(product),
    product.amazon?.variationThemeName || '',
    product.amazon?.modelNumber || '',
    product.amazon?.modelName || '',
    product.amazon?.style || '',
    product.amazon?.bulletPoint || '',
    product.amazon?.footwearSizeSystem || '',
    product.amazon?.footwearAgeGroup || '',
    product.amazon?.footwearSizeClass || '',
    product.amazon?.footwearWidth || '',
    product.amazon?.footwearSize || '',
    product.amazon?.soleMaterial || '',
    product.amazon?.toeStyle || '',
    product.amazon?.heightMap || '',
    product.amazon?.heelType || '',
    product.amazon?.waterResistanceLevel || '',
    product.amazon?.closure || '',
    product.amazon?.shaftCircumference || '',
    product.amazon?.shaftHeight || '',
    product.amazon?.skipOffer || '',
    product.amazon?.itemCondition || '',
    product.amazon?.listPriceCurrency || '',
    product.amazon?.dangerousGoodsRegulations || '',
    product.amazon?.outerMaterial || '',
    product.amazon?.departmentName || '',
    product.amazon?.sizeSystem || '',
    product.amazon?.sizeClass || '',
    product.amazon?.bodyType || '',
    product.amazon?.heightType || '',
    product.amazon?.fabricType || '',
    product.amazon?.specialSize || '',
    product.amazon?.weaveType || '',
    product.amazon?.careInstructions || '',
    product.amazon?.shippingTemplateSA || '',
    product.amazon?.fitType || '',
    product.amazon?.riseStyle || '',
    product.amazon?.closureType || '',
    product.amazon?.occasion || '',
    product.amazon?.subtype || '',
  ];
};

export const buildActivePlatformProductExportCsvRow = (product, sellerName) => {
  const base = buildProductExportCsvRow(product);
  return [
    sellerName || '',
    product.sellerId ? String(product.sellerId) : '',
    ...base,
    product.status || '',
    product.marketPlace || '',
    product.source || '',
    product.productType || '',
    product.countryOfOrigin || '',
    product.isFrozen === true ? 'true' : product.isFrozen === false ? 'false' : '',
    product.syncedAt ? new Date(product.syncedAt).toISOString() : '',
    product.createdAt ? new Date(product.createdAt).toISOString() : '',
    product.updatedAt ? new Date(product.updatedAt).toISOString() : '',
  ];
};
