export const mapProductToChannelEngine = (product) => {
  const customAttributes = [
    { Key: 'MarketPlace', Value: product.marketPlace, Type: 'TEXT', IsPublic: true, LanguageIsoCode: 'en' },
    { Key: 'Stock', Value: product.currentStockCount || 0, Type: 'TEXT', IsPublic: true, LanguageIsoCode: 'en' },
    {
      Key: 'categoryTrailAmazon',
      Value: product.categoryTrailAmazon || null,
      Type: 'TEXT',
      IsPublic: true,
      LanguageIsoCode: 'en',
    },
    {
      Key: 'categoryTrailNoon',
      Value: product.categoryTrailNoon || null,
      Type: 'TEXT',
      IsPublic: true,
      LanguageIsoCode: 'en',
    },

    {
      Key: 'nameAr',
      Value: product.nameAr || null,
      Type: 'TEXT',
      IsPublic: true,
      LanguageIsoCode: 'ar',
    },
    {
      Key: 'hsCodeSA',
      Value: product.hsCodeSA || null,
      Type: 'TEXT',
      IsPublic: true,
      LanguageIsoCode: 'en',
    },
    {
      Key: 'hsCodeAE',
      Value: product.hsCodeAE || null,
      Type: 'TEXT',
      IsPublic: true,
      LanguageIsoCode: 'en',
    },
    {
      Key: 'volumetricWeightCm',
      Value: product.volumetricWeightCm || 0,
      Type: 'TEXT',
      IsPublic: true,
      LanguageIsoCode: 'en',
    },
    {
      Key: 'descriptionAr',
      Value: product.descriptionAr || null,
      Type: 'TEXT',
      IsPublic: true,
      LanguageIsoCode: 'en',
    },
  ];
  const attributesString = product.attributes || '';
  return {
    ParentMerchantProductNo: product.parentProductSkuCode || null,
    ParentMerchantProductNo2: product.grandParentProductSkuCode || null,
    ExtraData: [
      { Key: 'Attributes', Value: attributesString, Type: 'TEXT', IsPublic: true, LanguageIsoCode: 'en' },
      ...customAttributes,
    ],
    Name: product.name,
    Description: product.description,
    Brand: product.brand,
    Size: product.size || '',
    Color: product.color || '',
    Ean: product.ean,
    Stock: product.currentStockCount || 0,
    ManufacturerProductNumber: product.productSkuCode,
    MerchantProductNo: product.productSkuCode,
    Price: product.price,
    MinPrice: product.minPrice,
    MaxPrice: product.maxPrice,
    MSRP: product.msrp,
    PurchasePrice: product.purchasePrice,
    VatRateType: product.vatRateType,
    ShippingCost: product.shippingCost,
    ShippingTime: product.shippingTime,
    Url: product.url,
    ImageUrl: product.imageUrl || '',
    CategoryTrail: product.categoryTrail,
    IsFrozen: false,
    ExtraImageUrl1: product.extraImageUrl1 || '',
    ExtraImageUrl2: product.extraImageUrl2 || '',
    ExtraImageUrl3: product.extraImageUrl3 || '',
  };
};
