export const OCP_STATUS_MAP = {
  CREATED: 'PENDING',
  EXPIRED: 'CANCELED',
  PENDING: 'PENDING',
  PAID: 'NEW',
  PAYMENT_INITIATED: 'PENDING',
  PAYMENT_AWAITING: 'PENDING',
  PAYMENT_FAILED: 'PAYMENT_FAILED',
  PAYMENT_PENDING: 'PENDING',
  PAYMENT_CANCELLED: 'PAYMENT_FAILED',
  PAYMENT_SUCCESS: 'NEW',
  AWAITING_SHIPMENT: 'IN_PROGRESS',
  PARTIALLY_AWAITING_SHIPMENT: 'IN_PROGRESS',

  // Return and Refund Events
  RETURN_REQUESTED: 'IN_PROGRESS',
  REFUNDED: 'CANCELED',

  // Cancellation Events
  CANCELLED_BY_CUSTOMER: 'CANCELED',
  CANCELLED_BY_SELLER: 'CANCELED',
  CANCELLED_SYSTEM: 'CANCELED',

  // Other
  FRAUD_REVIEW: 'PENDING',
  PROCESSING: 'IN_PROGRESS',
  BACKORDERED: 'PENDING',
  DISPUTED: 'PENDING',

  SHIPMENT_CREATED: 'SHIPPED',
  PARTIAL_SHIPMENT_CREATED: 'SHIPPED',
  PICKED: 'IN_PROGRESS',
  PARTIALLY_PICKED: 'IN_PROGRESS',
  OUT_FOR_DELIVERY: 'SHIPPED',
  PARTIALLY_OUT_FOR_DELIVERY: 'SHIPPED',
  DELIVERED: 'DELIVERED',
  PARTIALLY_DELIVERED: 'SHIPPED',
  NOT_DELIVERED: 'SHIPPED',
  PARTIALLY_NOT_DELIVERED: 'SHIPPED',
  SHIPMENT_REPROCESSING: 'IN_PROGRESS',
  CANCELLED: 'CANCELED',
  PARTIALLY_CANCELLED: 'IN_PROGRESS',
  PARTIAL_SHIPMENT_REPROCESSING: 'IN_PROGRESS',
};
