/**
 * ChannelEngine Webhook Event Constants
 */
export const CHANNEL_ENGINE_EVENTS = Object.freeze({
  ORDERS_CREATE: 'ORDERS_CREATE',
  ORDERS_CHANGE: 'ORDERS_CHANGE',
  RETURNS_CREATE: 'RETURNS_CREATE',
  RETURNS_CHANGE: 'RETURNS_CHANGE',
  SHIPMENTS_CREATE: 'SHIPMENTS_CREATE',
  SHIPMENTS_CHANGE: 'SHIPMENTS_CHANGE',
  NOTIFICATIONS_CREATE: 'NOTIFICATIONS_CREATE',
  BUNDLE_PRODUCTS_CHANGE: 'BUNDLE_PRODUCTS_CHANGE',
});

export const SUPPORTED_ORDER_EVENTS = [CHANNEL_ENGINE_EVENTS.ORDERS_CREATE, CHANNEL_ENGINE_EVENTS.ORDERS_CHANGE];
