export const formatGurmanProduct = (product, sellerId) => ({
  sellerId,
  parentProductId: null,
  parentProductSkuCode: null,
  productSkuCode: product.ws_code?.trim() || product.code?.trim(),
  name: product.name?.trim(),
  titleAr: null,
  description: product.details?.trim() || '',
  brand: product.brand?.trim() || '',
  attributes: product.model?.trim() || '',
  ean: product.barcode?.trim() || '',
  price: Number(product.price_special_vat_included || product.price_list_vat_included || 0),
  minPrice: Number(product.price_special || product.price_list || 0),
  maxPrice: Number(product.price_list_vat_included || 0),
  msrp: Number(product.price_list_vat_included || 0),
  purchasePrice: Number(product.price_list || 0),
  vatRateType: 'STANDARD',
  status: product.active === '1' ? 'active' : 'inactive',
  shippingCost: 0,
  shippingTime: null,
  url: product.image_url || '',
  categories: [],
  categoryTrail: product.category_path?.trim() || '',
  marketPlace: null,
  images: product.img_item?.[1] || null,
  currentStockCount: Number(product.stock || 0),
  volumetricWeightCm: Number(product.desi || 0),
  hsCodeAE: '',
  hsCodeSA: '',
  size: product.article || '',
  color: product.color_new || '',
  extraImageUrl1: product.img_item?.[1] || null,
  extraImageUrl2: product.img_item?.[2] || null,
  extraImageUrl3: product.img_item?.[3] || null,
  updatedAt: new Date(),
});
